apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: openmrsdbdata-pvc
  name: openmrsdbdata-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openmrsdbdata-pv
spec:
  storageClassName: standard
  claimRef:
    name: openmrsdbdata-pvc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/bahmni/openmrsdbdata'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openmrsdb
    environment: local
  name: openmrsdb
spec:
  selector:
    matchLabels:
      app: openmrsdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openmrsdb
        environment: local
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: openmrs
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: openmrs-user
          image: mysql:5.7
          name: openmrsdb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: openmrsdbdata
      restartPolicy: Always
      volumes:
        - name: openmrsdbdata
          persistentVolumeClaim:
            claimName: openmrsdbdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openmrsdb
spec:
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
  selector:
    app: openmrsdb
    environment: local
  type: ClusterIP