apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-checker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-checker

rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "statefulsets", "pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-checker-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: status-checker
subjects:
- kind: ServiceAccount
  name: status-checker
